### ISSUE TITLE
getAlbumPages doesn't work for albums with more than 50 but less than 100 images

### ISSUE THREAD

**Issue by tomdbarker** [RobK/photobox-downloader#1]
The fix for this is simply to change the line:

if (album.count > 100) {
          pageLinks.push(pageLink);

to:

if (album.count > thumbsPerPage) {
          pageLinks.push(pageLink);

**Comment by RobK** [comment]
I somehow missed this, thanks for the report and bug fix, much appreciated. I'll push an update to GitHub and NPM with the fix.

**Comment by RobK** [comment]
Fix pushed to master

**Comment by RobK** [comment]
Fix pushed to master
