### ISSUE TITLE
Does not work for photobox.co.uk

### ISSUE THREAD

**Issue by tharglet** [RobK/photobox-downloader#17]
Attempted to use this tool to download albums from photobox.co.uk, but it didn't work out of the box. After debugging, I found some pages on the .co.uk site come up with a maint page for http, most notably album pages.

Have fixed it by switching the urls all to https in a fork, but not sure if this is the most desired solution, so opening this up as an issue if someone wants to program an http/https switching option. If not, I can open a PR from https://github.com/tharglet/photobox-downloader for the simple fix.

**Comment by RobK** [comment]
Thanks for the report. I have fixed the issue (and some other small cosmetic issues) and published a new version.
