### ISSUE TITLE
Error on OSX

### ISSUE THREAD

**Issue by russellf9** [RobK/photobox-downloader#5]
Running the `pbdl` script on OSX got the error:
```
env: node\r: No such file or directory
```

I did some research and this is caused by a JS file having DOS line breaks rather than Unix line breaks.

As a workaround I used [dos2unix](https://www.npmjs.com/package/dos2unix) to fix the JS file:

```
sudo dos2unix /usr/local/lib/node_modules/photobox-downloader/photobox-dl.js
```

Perhaps it would be beneficial to encode the file for Unix users?

I know VIM can do that converting - "\r\n" to "\n"

Thanks for the great tool - my photos are downloading now! - russellf9

**Comment by RobK** [comment]
Thanks for the bug report. Git should have stripped the Windows style line endings on commit. I'll make a release this weekend from my Debian box to resolve the issue.

Cheers,
Robert

**Comment by russellf9** [comment]
Hi Robert 

Thanks for the email, glad to be of help

Russell

**Comment by RobK** [comment]
Fixed with commit: https://github.com/RobK/photobox-downloader/commit/64b53befcf25e07671c18f9ef8d8f510c7f880dc

Have published updated version to npm repo as well (npm update -g photobox-downloader)

Thanks again for the report.
