### ISSUE TITLE
Only getting albums on the first page

### ISSUE THREAD

**Issue by toadjaune** [RobK/photobox-downloader#8]
When we reach a number of albums important enough (happened from the 17th album for me), Photobox starts displaying them over several pages (just like it does for the different pages of a single album).

So far, it seems that the getAlbumList function only parses the first page.

**Comment by ejm1974** [comment]
Did you manage to find a solution for this?

**Comment by toadjaune** [comment]
It's a bit old, I'm not entirely sure, but I think I ended up calling manually the function for importing a specific album with the name of each album.
